### ISSUE TITLE
Gates are behaving weird from schems

### ISSUE THREAD

**Issue by FarmerThanos** [Goobrr/Esoterum#39]
Sometimes, gates apparently have a weird orientation with no inputs, however the visual ones are sometimes present. This means that some schems need to be "repaired" by rotating each gate 360 degrees. I am not entirely sure on how to reproduce this bug, but I know it happens with my ALU.

Cursed singular input AND gate and AND gate with both input original inputs true.
![image](https://user-images.githubusercontent.com/59265546/135301666-7647df57-fc27-40ac-a110-da5d3a535910.png)

XOR gate ignoring input.
![image](https://user-images.githubusercontent.com/59265546/135302512-1d1581b3-ceff-4d86-b751-baefdc0f45a3.png)

XOR gate accepting input properly after rotating 360 degrees, however visual connections stay on all sides.
![image](https://user-images.githubusercontent.com/59265546/135302741-e71c2ade-57bc-4db5-8fb5-46aa73ed7f65.png)

ALU Schematic (side multiplexer not included):
`bXNjaAF4nHWZ248bSRnFy27bbff9fu+2eU9WLEJC4gEUsfAEGZQNEhLiYZJ42UGTceSZsOR/D4T66jfOuI0dZXSmum7nnKrv6+oa9TO1sdTs7vr9Vvm/fHPzsHnxx79sXj//+bfKfbe9f7u/+fBws7tTSi1ur99sb++V87ff3+8etvuP7/++Uv728ffnP93st8r7Wnzx8ruj0sur1yr+Wvrnx7u3ZlD7/fb+/vofW5V+rXu7u3vY725vt3sVfn24333UvxxNdrd7dzzZX69eKWX9SpNUSzWZaFgt1FSD/FhSVo4y4FLtnVb7VAdAKFUTtVyY4nQqhdWhoDSa0SYymqXBk98nyj8eVB4E41kmelwDERArNdOwnk1U8+03m6t/bfc/3O5+2jz/jfOLbza/u97vP+nfrbkeQDOZKQWBxx89psaVMkVHHk3hMxU+UvKF7FRYHIhP9Zya2VQlMLPk+USep8pABuRAAZRABdRAA7RAB/TAAKwFLL0i07mG1TkJUu/QzJVHluZuwFfWQkOglPQNn/oe/k2VrSsiW4b48uXLZzNULPotlUhTS6VjkRbqLNRZqLNQZ6HOQp2FOgt1Fuos1Fmos1D3yGpm1l/DFLCAGTAHFoCtJqJmKWPMZP3mGhwEHhujt59+5h5rkJbeuZYyrt7B0iE47iBtQ2aIxvYf/s3EM6lPqFdHYzNuKr/P5dFCw0qGnus1U/LQpc6TpnPNwDwMxO25rNlhEGsifSKqYxonQApkQA4UQAlUQA00QAt0QA8MgFmZhTAW06c6vIrvf7x5ePhkUtubT5vXP17fXT/s7i1pNqP1HFgAtpi5kLB7CuC5frA655KlKxz5ZTFeLls/8Gy9Of+j2CKLQ4ow9ZbUB7KBZ7rNf5WMH54PkoU2byqQACksMyCXXb/QrpmWJQ8roAYaoAU6oAcGwLhmM6ktW9nWsDT0DCMprkTNZ/3zRUkjhy6ubA1bNpqUIiBhnBTIaGmY2jC1hamUKko1TRqgBTqgBwbAMF3CdEnkLYm8pUSeZQJHSWnOwwVgy05fHnKpUuMIWuq9beovxOLyNBaXl2JxSSwux7EotEKGip621cQwi2GdwDpFWAbk1BXUlZQqSjWlhlKLzA7ogQEwnq2YVOsEZsBKRlkR0ytiekVMr4jplcS0QAgkQApkQA4UQAU0QCfgMLvD7A6zO6yRwxo5BJ5zGnjOpcBzCDznNPAcAu+z4kXunAaecxx4MozZvA7KHJQ5KHNEmQxRHHEyD8qjZbRkkEqZTFDzVmsYspVJHSxwae5igYsFrrZgKlE0CjZ3HGwuweayPC4r4cLXha8LX5eVcFkJV++YqRxUqjF7V9Vj9q7w1QlM8zUv406ZWXth79HOg7ZHrHnEmieMBeQVoWFBnYk171KsecSadynWvNNY8y7Fmkeseaex5hFr3iHWDocAj1jzJNYEUlhnCMuBAiiBCqilv6easY+easc+euKczvvaOTPyIFP7NPAxUJ/LgBkwB0wY+oShzzr7hKFPGPqEoc/i+7wTfPaAzx7wUeKjxEeJjxIfJb4oEWiAVnT5qhvr8lV/rEu/ubQSw2EtggJqAgQFCAoQFCAoYCsEhHRwGtLBpZAOCOngNKSDcUgHpyEdjEM64OATHB98nrahNI8PZ8cvprnZEIFsCIFMWgXYGGBjgI0BNgbYGGBjIDYKdEAPrAVCZg3xKsSrEK9CvArlnCJv0FEKCMcpICQFhLI19PHq/FlBHyF4A4fsi5B9EbIvQgSFCAoRFCIoRFCIoBBBIYJCBIUIipgtQlCEoIh0EJEOIkkHAnIM02DSQXQpHUSkg+hSOohO00F0KR1EpIPoNB1EpINolA5M+xjWCXRTIKNxfhQCRmKBUm2btKpoXAMN0AId0CPfJIEI92JGjHEvxr3YfMxpmAFzYAGYzBCTGWIyQ0xmiMkMsYSgHK3D85s91h9Kj+fQiTmCx+e/J2N8iMUH+T7NxgbEsn0WGgomrWBSAw3QAh3QAwNgDEgYMcGABAMSDEgwIMGABAMSUkhymkKSSykkIYUkpykkGaeQZJxC5HQd8Gly1kapuOBbwidncvjkPBiWSNhJdU6rgjN8yWDVE3v1lb2wrJ+ygLRrzrGRwVvc6YAeGABjdUrzFKtTrE6xOsXqFKtTrE71/FP5Kjt74SDH+VFKSklJKXsyZU+mXKakvK1S3lappAsZOD63ZBNdkYytS4Wu/oaXWBTIgQIo+Xas/v+jdmoq6vOJJmWTpjiX4lyKcynOpTiX0TPDuQznMpzLcC7DuUycky9Y+9wyyUeafKpokGO3BgdwAY8hQiACElGekYwyDMgwIMOATAwQqPh4rs/5ICM1kjkySUpS6hi+BwZgLSGds48fb0bMS0LAAmbAHFgANmDE5YjLEZcjLmc75GyHXA4L0iGkX0S/WG5DctJOjuIcxTmKcxTnKM5JurkkXbkuaM6ts9S3DN8xZ0/JKM5FsXX4Wn68BCpQXKC4QHGB4gLFBYoLFBcoLlBcoLhAcYHiAsUFigsUF7xwClEss6fUZUAOFEAJVECtzJdz8xR/clHSns8NBYtcoLVkdR9vBkq0lmgt0VqitURridYSrSVaS7SWaC3RWqK1RGuJ1hKtJVpLVrcUrTJ7RikHCqAEKqDm+ufs6sq4JnxLNJZorND4eI1n3kxyCWJRmgFzYAHYgNFYobFCY4XGCo0VGis0Vmis0FihsUJjxXpWolFmzykVQAlUQE33hqFboAOMsIpMVJNtarJNTZ6uJU8LLAFDvoZ8Dfka8jXka8jXfOjWZJqafV+zJWpcq3mf1zCrYVbDrOZWoeZWoYZgw7I03MQ05tWqwZLIbnC+wfkG5xucb7gDbbjDbiDfQL6BfAP5BvINzjc433CT2HCT2HAn1nDT1JDJGvQ16GvQ16Cv4VXQQr6FfAv5lrNsK+Tl0mzOXfACsIElYMi3kG8h30K+hXwL+RbyLeRbyLeQbyHfQr6FfEtuaiHfQr6FfAv5DvId5DvId5DvcL4T8nLjt6BkA0vAkO8g30G+g3wH+Q7yHeQ7yHeQ7yDfQb6DfAf5DvIdOaeDfAf5DvI95HvI95DvId9Dvsf5XsjLdaVNaQkY8j3ke8j3kO8h30O+h3wP+R7yPeR7yPeQ7yHfQ76HfE9O6SHfC/mZHOhnE/XbP328fbj5cLv993a/+XBzdy9/uvnDfvd+82b38KDhYaf/f/i183J39ednmxfv3j3bfP/xzbPN1StdevmduXw1agbUDKgZUDOgZkDNwB+nBs4KAxE8QHyA+ADxAeIDxAduVgdcX3PfvebabS3f6HKhatuP+VXy7ZqsstacpnKb7pz/68tauabX44l6DaM1X5obWc+JBuv4CC4PZsfnvJl+MNdOzrRDH5R0W9DNPu22PO220t0sbamSWueo+VQeuMe3FzKup1dMgy+99BqYuQLmCk/nik7ninWv6dWriXRK6JSedspOO+WGoF7l/wE9RDJZ`

**Comment by FarmerThanos** [comment]
Update: Its something with rotation.

**Comment by Goobrr** [comment]
@MEEPofFaith fix your configs ~~i dont really know how your gates work~~

**Comment by MEEPofFaith** [comment]
The lengths of IntSeqs aren't properly saved when you close and re-open the game.
Buffer Gates and Note Blocks had the same issue.
